mysql:
  uri: localhost/database
  user: user
  password: password

player-identifier:
  field: minecraft_username
  name-system: true
  use-profile-fields: true
  database-table: xf_user_field_value
  table-xenid: user_id
  table-playerid: minecraft_username

member-feature:
  enable: false
  require-valid-email: true
  default-group-name: default

sync-task-delay: 10 # Time is in minutes 10 is 10 minutes.
debug: false # Only enable if needed.